name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      example_api_domain:
        description: "Example API domain for E2E tests"
        required: false
        default: "https://vercel-bun-nine.vercel.app"
        type: string
      bench_api_domain:
        description: "Bench API domain for E2E tests"
        required: false
        default: "https://vercel-bun-bench.vercel.app"
        type: string

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd example && bun install && cd ../bench && bun install

      - name: Run E2E tests
        run: bun run e2e
        env:
          E2E_EXAMPLE_API_DOMAIN: ${{ inputs.example_api_domain || 'https://vercel-bun-nine.vercel.app' }}
          E2E_BENCH_API_DOMAIN: ${{ inputs.bench_api_domain || 'https://vercel-bun-bench.vercel.app' }}
